#!/bin/bash

npm i

cp -v node_modules/turndown/dist/turndown.js .
cp -v node_modules/@mozilla/readability/Readability.js .
cp -v node_modules/webextension-polyfill/dist/browser-polyfill.js .

command=$1

if [[ $command = run ]]; then
    flags=--verbose
elif [[ $command = build ]]; then
    flags=--overwrite-dest
fi

node_modules/web-ext/bin/web-ext $command $flags \
    --ignore-files "**/*.xcf" \
    --ignore-files "*LICENSE*" \
    --ignore-files "README.md" \
    --ignore-files "package-lock.json" \
    --ignore-files "screenshots/*" \
    --ignore-files "web-ext" \
    --ignore-files "icons/original.png"
