#!/bin/bash

pushd turndown
npm i
npm run build
popd

npm i web-ext

command=$1

if [[ $command = run ]]; then
    flags=--verbose
elif [[ $command = build ]]; then
    flags=--overwrite-dest
fi

node_modules/web-ext/bin/web-ext $command $flags \
    --ignore-files "**/*.xcf" \
    --ignore-files "*LICENSE*" \
    --ignore-files "README.md" \
    --ignore-files "package-lock.json" \
    --ignore-files "web-ext" \
    --ignore-files "icons/original.png" \
    --ignore-files "readability/!(Readability.js)" \
    --ignore-files "turndown/!(dist)"
